FROM 	debian:buster

ARG		DOMAIN_NAME

RUN		apt-get update -y \
			&& apt-get upgrade -y

RUN 	apt-get install -y \
			nginx \
			git

COPY	conf/default.conf /etc/nginx/conf.d/default.conf

WORKDIR /var/www/
COPY	tools/website website

EXPOSE 8080

ENTRYPOINT	["nginx"]
CMD 		["-g", "daemon off;"]
